### ISSUE TITLE
Mention CommonMark (?)

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/modern-scientific-authoring#21]
From @sprossiter:

```
When talking about Markdown's lack of standardisation, is CommonMark worth a mention?
(I've no idea how much traction that is or isn't getting...)
```

**Comment by tpoisot** [comment]
Definitely maybe. The most common flavors seem to be Github, pandoc, then common (roughly in that order). They differ mostly in arcane ways, so they can be mentionned in a footnote somewhere.

**Comment by sprossiter** [comment]
@tpoisot I was really just talking about mentioning that standardisation efforts existed, not a comparison of flavours (though, as I said, I've no idea how much traction CommonMark is getting).
