### ISSUE TITLE
Mention reStructuredText (and others?)

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/modern-scientific-authoring#22]
From @sprossiter:

```
Maybe mention the plethora of other simple-markup languages (particularly reStructuredText)
as adding to the fragmentation there.
```

**Comment by moorepants** [comment]
Markdown is definitely winning the popularity contest, but restructuredtext has more features. I wrote my dissertation in restructuredtext, outputting a web page and the pdf in the format required by my uni. I don't think that is quite possible with markdown yet. Although things like this are popping up:
- https://github.com/smathot/academicmarkdown
- http://scholarlymarkdown.com/
- http://pubpub.media.mit.edu/

If I had to mention only one lightweight markup language for academic writing, it'd definitely be restructuredtext at this point in time.

**Comment by wking** [comment]
On Fri, Feb 12, 2016 at 02:55:42PM -0800, Jason K. Moore wrote:

> Markdown is definitely winning the popularity contest, but
> restructuredtext has more features. I wrote my dissertation in
> restructuredtext, outputting a web page and the pdf…

I'd expect most PDF generation in Markdown / reStructuredText
toolchains goes through pdflatex or Pandoc.

> If I had to mention only one lightweight markup language for
> academic writing, it'd definitely be restructuredtext at this point
> in time.

“academic writing” is such a big net ;).  I'd agree that vanilla
Markdown alone is not going to get you an easy disseration.  But for
article-length writing it's probably fine, and it's nice to have a
language that you can also use for GitHub issues and similar channels.

For the initial intro, I think there is a benefit to picking the
lightest-weight, useful language (and I think that's Markdown).  Once
you get out beyond a few dozen pages, you'll want to be using
something like reStructuredText or LaTeX that is designed with that
sort of large, cross-referenced, auto-numbered, possibly multi-file
construction in mind.

reStructuredText vs. LaTeX is probably a wash.  I found it a lot
easier to get good-looking HTML out of reStructuredText than to get it
out of LaTeX, but LaTeX is so well established.  I think swapping
reStructuredText in for 03-advanced.md would be a workable lesson, and
which would be better would probably depend on the learner's
environment / community.
