### ISSUE TITLE
Does this lesson have to depend on command-line skills?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/modern-scientific-authoring#30]
Both LaTeX and Markdown+Pandoc workflows require command-line skills, but we'd like this lesson to be accessible to the same audience as Data Carpentry's (no shell).

**Comment by petebachant** [comment]
A LaTeX IDE, e.g., [TeXstudio](http://texstudio.org), can keep the command line away, and even has some way to integrate with Subversion, which I guess can be [hacked a bit to use Git](http://alloy2smt.blogspot.com/2013/01/using-texstudio-with-git.html). Users could also use the GitHub app or some other Git GUI, though Git is a prerequisite.

Atom has some pandoc plugins available, but it seems more trouble to setup than using the command line or a Makefile. Atom's built-in HTML Markdown previewer is helpful though, and can copy/save as HTML, which should be fine enough if the objective is to use Markdown for web and LaTeX for PDFs. 

To the initial question, I think yes, command line skills are necessary, but this really means having the ability to open a terminal or command prompt in the proper directory and type either pandoc, LaTeX (`latexmk -pdf my_paper.tex` is usually enough for me), and/or Git commands.
