### ISSUE TITLE
journals don't add value

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/modern-scientific-authoring#42]
http://arxiv.org/abs/1604.05363

**Comment by wking** [comment]
On Fri, Jun 10, 2016 at 06:58:32PM -0700, Greg Wilson wrote:

> http://arxiv.org/abs/1604.05363

I don't see them addressing papers which are not published at all
because they didn't pass peer review.  Although publication bias is a
mixed blessing ;).
